# **Final Assignment**
In this assignment, you will implement K-Nearest Neighbour (KNN) and Ordinary Least Square (OLS) regression methods. Download the [excel file](https://docs.google.com/spreadsheets/d/17f6h4h-4x6XMuI4Budcw4Ujoxd0ceogv). The dataset contains 11 columns: `"bedrooms"`, `"bathrooms"`, `"sqft_living"`, `"sqft_lot"`, `"floors"`, `"condition"`, `"grade"`, `"sqft_above"`, `"sqft_basement"`, `"age"`and `"price"`.
Use `pd.read_excel()` to read the file and make prediction of whether a given house is likely to be expensive based on the features related to the house.

Use KNN and OLS regression independently to determine and compare their performance in terms of accuracy and confusion matrix.

To accomplish this task, you will have to convert the values under `"price"` into one of two possible values: **1** and **0** denoting "expensive" and "cheap" respectively. For this, if the price of the house is less than `450000`, it is "cheap"; otherwise it is "expensive" . 

**Note:**This conversion must be done before training for KNN, and after conversa for OLS regression, on each predicted `"price"`.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix, accuracy_score

from google.colab import drive
drive.mount('/content/drive')
Dataset = pd.read_excel("/content/drive/MyDrive/Dataset/house_data.xlsx")

Dataset["price"] = np.where(Dataset["price"] >= 450000, 1, 0)

X_train, X_test, y_train, y_test = train_test_split(Dataset.drop("price", axis=1), Dataset["price"], test_size=0.2, random_state=42)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# implement KNN algorithm on the training set.
# Implement KNN
k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

# Make prediction
y_pred_knn = knn.predict(X_test)

# Calculate accuracy
acc_knn = accuracy_score(y_test, y_pred_knn)
cm_knn = confusion_matrix(y_test, y_pred_knn)

print("KNN Accuracy: ", acc_knn)
print("KNN Confusion matrix: ")
print(cm_knn)


KNN Accuracy:  0.7281980106407587
KNN Confusion matrix: 
[[1570  534]
 [ 641 1578]]


In [ ]:
#implement OLS regression on the training set
# Implement OLS regression
ols = LinearRegression()
ols.fit(X_train, y_train)

# Make predictions on the testing set
y_pred_ols = ols.predict(X_test)
y_pred_ols = np.where(y_pred_ols>=0.5, 1, 0)

# Calculate accuracy and confusion matrix
acc_ols = accuracy_score(y_test, y_pred_ols)
cm_ols = confusion_matrix(y_test, y_pred_ols)

print("Accuracy of OLS regression: ", acc_ols)
print("Confusion matrix of OLS regression: ")
print(cm_ols)


Accuracy of OLS regression:  0.7883414295628036
Confusion matrix of OLS regression: 
[[1797  307]
 [ 608 1611]]


In [ ]:
print("Accuracy comparison: ")
print("KNN: ", acc_knn)
print("OLS regression: ", acc_ols)

print("\nConfusion matrix comparison: ")
print("KNN: ")
print(cm_knn)
print("OLS regression: ")
print(cm_ols)


Accuracy comparison: 
KNN:  0.7281980106407587
OLS regression:  0.7883414295628036

Confusion matrix comparison: 
KNN: 
[[1570  534]
 [ 641 1578]]
OLS regression: 
[[1797  307]
 [ 608 1611]]
